name: Run Smoke Tests
on: 
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Smoke Tests
        id: smoke-tests
        run: |
          TEST_REGION=us-slc
          SKIP_KAFKA_TESTS=true
          SKIP_VAULT_TESTS=true
          PAPERTRAIL_DRAIN="syslog+tls://foobar.com"
          ANOMALY_METRICS_DRAIN="syslog+tls://foobar.com"
          AKKERIS_APP_CONTROLLER_URL=http://localhost:5000
          ALAMO_APP_CONTROLLER_URL=http://localhost:5000
          DEFAULT_GITHUB_TOKEN=12345
          DEFAULT_GITHUB_USERNAME=akkerisbot
          DOCKER_REGISTRY_AUTH='{}'
          LOG_SESSION_URL=http://logsession.akkeris-system.svc.cluster.local
          LOG_SHUTTLE_URL=http://logshuttle.akkeris-system.svc.cluster.local
          SUPPORT_EMAIL=support@akkeris.io
          NGROK_TOKEN='${{ secrets.NGROK_TOKEN }}'
          AKKERIS_API='${{ secrets.AKKERIS_API }}'
          AKKERIS_API_URL='${{ secrets.AKKERIS_API_URL }}'
          AKKERIS_UI_URL='${{ secrets.AKKERIS_UI_URL }}'
          AUTH_KEY='${{ secrets.AUTH_KEY }}'
          BUILD_SHUTTLE_URL='${{ secrets.BUILD_SHUTTLE_URL }}'
          DATABASE_URL='${{ secrets.DATABASE_URL }}'
          DOCKER_REGISTRY_HOST='${{ secrets.DOCKER_REGISTRY_HOST }}'
          DS1_STACK_API='${{ secrets.DS1_STACK_API }}'
          ENCRYPT_KEY='${{ secrets.ENCRYPT_KEY }}'
          ENCRYPT_KEY_192_BITS='${{ secrets.ENCRYPT_KEY_192_BITS }}'
          ES_URL='${{ secrets.ES_URL }}'
          JWT_RS256_PRIVATE_KEY='${{ secrets.JWT_RS256_PRIVATE_KEY }}'
          JWT_RS256_PUBLIC_CERT='${{ secrets.JWT_RS256_PUBLIC_CERT }}'
          ALAMO_BASE_DOMAIN='${{ secrets.ALAMO_BASE_DOMAIN }}'
          SITE_BASE_DOMAIN='${{ secrets.SITE_BASE_DOMAIN }}'
          BASE_DOMAIN='${{ secrets.BASE_DOMAIN }}'
          US_SLC_REGION_API='${{ secrets.US_SLC_REGION_API }}'
          wget https://nodejs.org/download/release/latest-v14.x/node-v14.17.0-linux-arm64.tar.gz
          tar zxvf node-v14.17.0-linux-arm64.tar.gz
          rm node-v14.17.0-linux-arm64.tar.gz
          PATH=$PATH:$PWD/node-v14.17.0-linux-arm64/bin/
          rm -rf node-v14.17.0-linux-arm64
          npm cover