name: Run Smoke Tests
on: 
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Smoke Tests
        id: smoke-tests
        run: |
          export TEST_REGION=us-slc
          export SKIP_KAFKA_TESTS=true
          export SKIP_VAULT_TESTS=true
          export PAPERTRAIL_DRAIN="syslog+tls://foobar.com"
          export ANOMALY_METRICS_DRAIN="syslog+tls://foobar.com"
          export AKKERIS_APP_CONTROLLER_URL=http://localhost:5000
          export ALAMO_APP_CONTROLLER_URL=http://localhost:5000
          export DEFAULT_GITHUB_TOKEN=12345
          export DEFAULT_GITHUB_USERNAME=akkerisbot
          export DOCKER_REGISTRY_AUTH='{}'
          export LOG_SESSION_URL=http://logsession.akkeris-system.svc.cluster.local
          export LOG_SHUTTLE_URL=http://logshuttle.akkeris-system.svc.cluster.local
          export DS1_STACK_API="https://region-api.akkeris.io"
          export US_SLC_REGION_API="https://region-api.akkeris.io"
          export BUILD_SHUTTLE_URL="https://builds.akkeris.io"
          export SUPPORT_EMAIL=support@akkeris.io
          export NGROK_TOKEN='${{ secrets.NGROK_TOKEN }}'
          export AKKERIS_API='${{ secrets.AKKERIS_API }}'
          export AKKERIS_API_URL='${{ secrets.AKKERIS_API_URL }}'
          export AKKERIS_UI_URL='${{ secrets.AKKERIS_UI_URL }}'
          export AUTH_KEY='${{ secrets.AUTH_KEY }}'
          export DOCKER_REGISTRY_HOST='${{ secrets.DOCKER_REGISTRY_HOST }}'
          export ENCRYPT_KEY='${{ secrets.ENCRYPT_KEY }}'
          export ENCRYPT_KEY_192_BITS='${{ secrets.ENCRYPT_KEY_192_BITS }}'
          export ES_URL='${{ secrets.ES_URL }}'
          export JWT_RS256_PRIVATE_KEY='${{ secrets.JWT_RS256_PRIVATE_KEY }}'
          export JWT_RS256_PUBLIC_CERT='${{ secrets.JWT_RS256_PUBLIC_CERT }}'
          export ALAMO_BASE_DOMAIN='${{ secrets.ALAMO_BASE_DOMAIN }}'
          export SITE_BASE_DOMAIN='${{ secrets.SITE_BASE_DOMAIN }}'
          export BASE_DOMAIN='${{ secrets.BASE_DOMAIN }}'
          export DATABASE_URL='${{ secrets.DATABASE_URL }}'
          sudo apt-get -y install nodejs npm
          node -v
          npm install
          npm run cover